### ISSUE TITLE
Error: The directory name is invalid

### ISSUE THREAD

**Issue by pocki** [devlead/ARI#7]
I am getting an error running the inventory command. 

```
2024-02-26 14:12:34 info: ARI.Commands.InventoryCommand[0]
      Getting subscriptions...
2024-02-26 14:12:34 info: ARI.Commands.InventoryCommand[0]
      Found 2
Error: The directory name is invalid. : 'C:\AzureResourceInventory\xxx.onmicrosoft.com\hidden-link:
\app-insights-conn-string'
```

This error may come from a resource which has some special tags like 'hidden-link: /app-insights-conn-string'

.NET SDK 8.0.201
ARI latest version, installed today

Do you need more informations?

**Comment by devlead** [comment]
This is fixed in version  [2024.3.19.67](https://github.com/devlead/ARI/releases/2024.3.19.67)

**Comment by pocki** [comment]
Thank you very much. 
But now I am getting this error:
```
2024-03-20 10:08:58 info: ARI.Commands.InventoryCommand[0]
      Getting subscriptions...
2024-03-20 10:08:58 info: ARI.Commands.InventoryCommand[0]
      Found 2
Error: Cannot combine a directory path with an absolute directory path.
```

**Comment by devlead** [comment]
@pocki added some more logging in release [2024.3.25.72](https://github.com/devlead/ARI/releases/tag/2024.3.25.72), could you take it for a spin so we cab see if we get some more details into the error you're getting.

**Comment by devlead** [comment]
Excellent👍
